version: '3'

services:
  job_postings_etl:
    build:
      context: ./job_postings_etl
    env_file:
      - .env

  # chatbot_api:
  #   image: xuxx148/llm-chatbot-api
  #   build:
  #     context: ./chatbot_api
  #   env_file:
  #     - .env
  #   # depends_on:
  #   #   - hospital_neo4j_etl
  #   ports:
  #     - "8000:8000"

  # chatbot_frontend:
  #   image: xuxx148/llm-chatbot-frontend
  #   build:
  #     context: ./chatbot_frontend
  #   env_file:
  #     - .env
  #   depends_on:
  #     - chatbot_api
  #   ports:
  #     - "8080:8080"